spring:
  application:
    name: server
  datasource:
    url: "${SPRING_DATASOURCE_URL}"
    username: "${SPRING_DATASOURCE_USERNAME}"
    password: "${SPRING_DATASOURCE_PASSWORD}"
    driver-class-name: "org.postgresql.Driver"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 7140

github:
  client-id: "${GITHUB_CLIENT_ID}"
  client-secret: "${GITHUB_CLIENT_SECRET}"
  redirect-uri: "${GITHUB_REDIRECT_URI}"
