spring:
  application:
    name: server
  datasource:
    url: ${spring.datasource.url}
    username: ${spring.datasource.username}
    password: ${spring.datasource.password}
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
server:
  port: 7140
  tomcat:
    max-http-form-post-size: 100MB
    max-swallow-size: 100MB

github:
  client-id: "${github.client-id}"
  client-secret: "${github.client-secret}"
  redirect-uri: "${github.redirect-uri}"
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include:
          - prometheus